# Generated by Django 5.1.3 on 2025-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aichatsession_airequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='messages',
            field=models.CharField(),
        ),
    ]
